package pmInstance.model;
import java.util.Comparator;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="particulatematter")
public class PM {

	private String id;
	private double pm25;
	private double pm10;
	private double lat;
	private double lon;
	private long dateTime;
	
	
	@DynamoDBHashKey(attributeName="id")
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName="pm25")
	public double getPm25() {
		return pm25;
	}
	public void setPm25(double pm25) {
		this.pm25 = pm25;
	}
	
	@DynamoDBAttribute(attributeName="pm10")
	public double getPm10() {
		return pm10;
	}
	public void setPm10(double pm10) {
		this.pm10 = pm10;
	}
		
	@DynamoDBAttribute(attributeName="latitude")
	public double getLat() {
		return lat;
	}	
	public void setLat(double lat) {
		this.lat = lat;
	}
	
	@DynamoDBAttribute(attributeName="longitude")
	public double getLon() {
		return lon;
	}	
	public void setLon(double lon) {
		this.lon = lon;
	}
	
	
	@DynamoDBAttribute(attributeName="dateTime")
	public long getDateTime() {
		return dateTime;
	}
	public void setDateTime(long dateTime) {
		this.dateTime = dateTime;
	}
	
	public PM(String id, double pm25, double pm10,  double lat, double lon, long dateTime) {
		super();
		this.setPm25(pm25);
		this.setPm10(pm10);
		this.setDateTime(dateTime);
		this.setId(id);
		this.setLat(lat);
		this.setLon(lon);
	}
	
	public PM() {
		super();
		this.setPm25(5);
		this.setPm10(5);
		this.setDateTime(15);
		this.setId("default");
		this.setLat(10);
		this.setLon(10);
	}
	
	
	
}
